- name: Squid install
  apt: pkg=squid 

- name: Squid config copy
  copy: src=files/squid.conf dest=/etc/squid3/squid.conf

- name: Squid passwords copy
  copy: src=files/passwords_basic dest=/etc/squid3/passwords_basic

- name: Service restart
  command: service squid3 restart
  sudo: true

